### PR TITLE
Fix FrozenError on Embedded filter

### PR DESCRIPTION
**Pull request by r7kamura**
For https://github.com/r7kamura/slimi/issues/9

### CODE REVIEW

**Comment by Nerian** [comment]
can we have a new gem release for this? 🙏

**Comment by r7kamura** [comment]
Oh, sorry I forgot it. I'll release it soon 👍

**Comment by r7kamura** [comment]
Just released 0.7.4! Thank you for reminding me 🙏 

- https://rubygems.org/gems/slimi/versions/0.7.4
- https://github.com/r7kamura/slimi/releases/tag/v0.7.4

**Comment by Nerian** [comment]
Nice, thanks!

**Pull request merged**
